language: ruby
rvm:
  - "2.1.0"
env:
  global:
    - secure: "EqG1ea2hh4hoBZpq+VPgG1aheHr7xFEDyFxdpIuuZzXVjzL6MdCV2TFtleTnxlBtuwvlLQtOxWFhW6UROyugkwlSuGpXKDCGuQKjTZtLkjlYA0YnHOeUDQbwfElcKf+LEpFR8jI9dbrCwvcixaqlJHYaueMUMexKjaUmOXVWLDk="
    - secure: "REB+22ZogCMz9MTgeIHb/SnZ7fmM7F0iWAj9WteLh7BxoeBKxfgFHe45jkJ2rfXztUP+uNuLTD4JjD1W4TlqUpO5UmEQb7mIURucCtEojzfOPTOfqCYRTpjs1CPmzGnesiCgsK4i/3fXvg2GALeH6ISwkYI9cXsSZjAVtSJORFk="
    - secure: "kuSTAhiHRJ63O60VRK77R/iq2o5OrWOSB/SQnriUcbFiZrCo/LdfqVuJKA51SsDAH+doLHdhqXXjXhAM+RDnm6beRvj50WooMipZ73sXoF2W/pZm1jF4RBODhSOpbnSYdYlwIvS0ZnXyJqjIrW4Bo7MxQR3AKrlVEUOx6jHgfP8="
    - S3_BUCKET=static-stage.imago.in
    - BASE_LINK_URL=https://d29sc4udwyhodq.cloudfront.net/
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec